---
apiVersion: v1
kind: Secret
metadata:
  name: sysdig-key
  namespace: custom-metrics
type: Opaque
data:
  # Base64-encoded key (59493980-bbab-44e5-81b2-d80d59192fcd).
  # This is not a valid agent key.
  sysdig-key: NTk0OTM5ODAtYmJhYi00NGU1LTgxYjItZDgwZDU5MTkyZmNk

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: custom-metrics-apiserver
  namespace: custom-metrics
  labels:
    app: custom-metrics-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: custom-metrics-apiserver
    spec:
      tolerations:
      - key: beta.kubernetes.io/arch
        value: arm
        effect: NoSchedule
      - key: beta.kubernetes.io/arch
        value: arm64
        effect: NoSchedule
      serviceAccountName: custom-metrics-apiserver
      volumes:
        - name: sysdig-key
          secret:
            secretName: sysdig-key
      containers:
      - name: custom-metrics-server
        image: sevein/k8s-sysdig-adapter:latest
        command: ["adapter"]
        args:
        # TODO
        # - --deploymentname=kuard
        # - --servicename=kuard
        # - --kubernetesnamespace=default
        # - --targetmetric=net.http.request.count
        # - --metrics-relist-interval=30s
        - "--v=10"
        - "--logtostderr=true"
        volumeMounts:
        - name: sysdig-key
          mountPath: "/etc/sysdig-key"
          readOnly: true
        ports:
        - containerPort: 443
        securityContext:
          runAsUser: 0
